services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2023!"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "5432:5432"