app:
  name: test
  version: v0.0.1
logger:
  level: debug
  encoding: console #console or json
http:
  enabled: true
  port: 8080
db:
  enabled: true
  type: postgres
  showsql: true
  connectionstring: "host=localhost user=postgres password=mysecretpassword dbname=aruna port=5432"